import type {
  Client,
  Expense,
  Invoice,
  Machine,
  MaintenanceRecord,
  Payment,
  PayrollEntry,
  Quote,
} from "./types";

export const clients: Client[] = [
  {
    id: "andina",
    name: "Constructora Andina S.A.S.",
    contact: "Carlos Restrepo",
    phone: "314 552 8890",
    services: 7,
  },
  {
    id: "rionegro",
    name: "Municipio de Rionegro",
    contact: "Marcela Duque",
    phone: "301 447 2210",
    services: 4,
  },
  {
    id: "ceja",
    name: "Urbanizadora La Ceja",
    contact: "Fernando Gómez",
    phone: "310 890 4471",
    services: 5,
  },
  {
    id: "vialpisos",
    name: "Vialpisos Ltda.",
    contact: "Diana Correa",
    phone: "300 118 5523",
    services: 3,
  },
  {
    id: "guarne",
    name: "Inversiones Guarné",
    contact: "Julián Zapata",
    phone: "312 664 9081",
    services: 2,
  },
];

export const invoices: Invoice[] = [
  {
    id: "FAC-0182",
    clientId: "andina",
    machineCode: "EX-01",
    concept: "Alquiler excavadora EX-01 · 240 h · Vía Rionegro–La Ceja",
    amount: 28_400_000,
    status: "PARTIAL",
    date: "12 jul 2026",
    due: "Vencida 12 días",
    overdue: true,
    photo: true,
  },
  {
    id: "FAC-0189",
    clientId: "rionegro",
    machineCode: "MN-01",
    concept: "Nivelación de vía · motoniveladora MN-01 · 96 h",
    amount: 14_680_000,
    status: "PENDING",
    date: "18 jul 2026",
    due: "Vence 28 jul",
    overdue: false,
    photo: false,
  },
  {
    id: "FAC-0191",
    clientId: "ceja",
    machineCode: "VQ-02",
    concept: "Transporte de material · volqueta VQ-02 · 38 viajes",
    amount: 11_000_000,
    status: "PARTIAL",
    date: "20 jul 2026",
    due: "Vence 30 jul",
    overdue: false,
    photo: false,
  },
  {
    id: "FAC-0176",
    clientId: "vialpisos",
    machineCode: "RD-01",
    concept: "Compactación con rodillo RD-01 · 60 h",
    amount: 9_200_000,
    status: "PAID",
    date: "8 jul 2026",
    due: "Pagada 15 jul",
    overdue: false,
    photo: true,
  },
  {
    id: "FAC-0170",
    clientId: "andina",
    machineCode: "RX-01",
    concept: "Alquiler retroexcavadora RX-01 · 180 h",
    amount: 21_500_000,
    status: "PAID",
    date: "3 jul 2026",
    due: "Pagada 10 jul",
    overdue: false,
    photo: true,
  },
  {
    id: "FAC-0164",
    clientId: "guarne",
    machineCode: "CG-01",
    concept: "Cargador CG-01 · descapote 500 m³",
    amount: 7_620_000,
    status: "PAID",
    date: "1 jul 2026",
    due: "Pagada 6 jul",
    overdue: false,
    photo: true,
  },
];

/** Abonos parciales ya registrados contra facturas PARTIAL del seed. */
export const payments: Payment[] = [
  {
    id: "ABO-0001",
    invoiceId: "FAC-0182",
    amount: 10_000_000,
    date: "20 jul",
    note: "Anticipo a 30 días",
  },
  {
    id: "ABO-0002",
    invoiceId: "FAC-0191",
    amount: 5_000_000,
    date: "24 jul",
    note: "Primer abono",
  },
];

export const payroll: PayrollEntry[] = [
  { name: "Jhon Muñoz", role: "Operario excavadora EX-01", amount: 2_600_000, paid: true },
  { name: "Andrés Ceballos", role: "Operario retroexcavadora RX-01", amount: 2_450_000, paid: true },
  { name: "Wilmer Ospina", role: "Operario volqueta VQ-02", amount: 1_980_000, paid: true },
  { name: "Sebastián Ríos", role: "Operario rodillo RD-01", amount: 1_850_000, paid: false },
  { name: "Camilo Vélez", role: "Operario motoniveladora MN-01", amount: 2_120_000, paid: true },
];

export const expenses: Expense[] = [
  {
    id: "GAS-0431",
    cat: "SUELDO",
    desc: "Nómina de operarios · 2da quincena",
    amount: 11_000_000,
    date: "25 jul",
    machine: "—",
    photo: false,
  },
  {
    id: "GAS-0430",
    cat: "GASOLINA",
    desc: "Combustible flota · surtido semanal",
    amount: 4_600_000,
    date: "22 jul",
    machine: "EX-01",
    photo: true,
  },
  {
    id: "GAS-0429",
    cat: "REPUESTO",
    desc: "Cambio de filtros hidráulicos",
    amount: 2_450_000,
    date: "20 jul",
    machine: "EX-01",
    photo: true,
  },
  {
    id: "GAS-0428",
    cat: "REPARACION",
    desc: "Reparación sistema de frenos",
    amount: 3_100_000,
    date: "18 jul",
    machine: "VQ-02",
    photo: true,
  },
  {
    id: "GAS-0427",
    cat: "PUNTO",
    desc: "Papelería y viáticos de gerencia",
    amount: 620_000,
    date: "16 jul",
    machine: "—",
    photo: false,
  },
  {
    id: "GAS-0426",
    cat: "GASOLINA",
    desc: "Combustible motoniveladora",
    amount: 1_980_000,
    date: "14 jul",
    machine: "MN-01",
    photo: true,
  },
  {
    id: "GAS-0425",
    cat: "REPUESTO",
    desc: "Llantas rodillo RD-01",
    amount: 3_800_000,
    date: "11 jul",
    machine: "RD-01",
    photo: false,
  },
  {
    id: "GAS-0424",
    cat: "SUELDO",
    desc: "Nómina de operarios · 1ra quincena",
    amount: 11_000_000,
    date: "10 jul",
    machine: "—",
    photo: false,
  },
  {
    id: "GAS-0423",
    cat: "PUNTO",
    desc: "Alimentación cuadrilla obra Rionegro",
    amount: 480_000,
    date: "6 jul",
    machine: "—",
    photo: false,
  },
  {
    id: "GAS-0432",
    cat: "REPARACION",
    desc: "Cambio de bomba hidráulica · mantenimiento preventivo 18.000 h",
    amount: 4_200_000,
    date: "22 jul",
    machine: "EX-02",
    photo: true,
  },
];

/**
 * Foto real de la empresa — por ahora la única disponible. Se usa en todas
 * las máquinas (admin, catálogo público y galería) hasta que suban fotos
 * propias de cada activo desde la hoja del semáforo.
 */
const MACHINE_PHOTO = "/Maquinas/maquina_1.jpeg";

export const machines: Machine[] = [
  {
    code: "EX-01",
    name: "Excavadora CAT 320D",
    type: "Excavadora de orugas",
    status: "WORKING",
    location: "Vía Rionegro–La Ceja · K12+400",
    client: "Constructora Andina S.A.S.",
    hours: "14.820 h",
    since: "desde 12 mar",
    updated: "Hoy 06:40 · operario J. Muñoz",
    photo: MACHINE_PHOTO,
    suggestedRate: 120_000,
    publicDescription:
      "Excavadora de orugas de gran capacidad, ideal para excavación profunda, movimiento de tierra y demolición controlada en obras de infraestructura vial.",
    specs: [
      { label: "Potencia", value: "121 kW (162 HP)" },
      { label: "Peso operativo", value: "20.300 kg" },
      { label: "Capacidad de cucharón", value: "1,19 m³" },
      { label: "Alcance máx. de excavación", value: "9,9 m" },
      { label: "Año", value: "2019" },
    ],
  },
  {
    code: "RX-01",
    name: "Retroexcavadora CASE 580",
    type: "Retroexcavadora",
    status: "WORKING",
    location: "Urbanización La Ceja · Etapa 2",
    client: "Urbanizadora La Ceja",
    hours: "9.410 h",
    since: "desde 3 jul",
    updated: "Ayer 17:20 · operario A. Ceballos",
    photo: MACHINE_PHOTO,
    suggestedRate: 120_000,
    publicDescription:
      "Retroexcavadora versátil 2 en 1 — cargador frontal y brazo excavador — perfecta para obras urbanas, zanjeo y urbanizaciones por etapas.",
    specs: [
      { label: "Potencia", value: "74 kW (99 HP)" },
      { label: "Peso operativo", value: "7.700 kg" },
      { label: "Profundidad de excavación", value: "4,3 m" },
      { label: "Capacidad de cargador frontal", value: "1,03 m³" },
      { label: "Año", value: "2020" },
    ],
  },
  {
    code: "VQ-01",
    name: "Volqueta Kenworth 750",
    type: "Volqueta doble troque",
    status: "WORKING",
    location: "Cantera El Peñol",
    client: "Vialpisos Ltda.",
    hours: "186.400 km",
    since: "desde 20 jul",
    updated: "Hoy 05:55 · operario W. Ospina",
    photo: MACHINE_PHOTO,
    suggestedRate: 90_000,
    publicDescription:
      "Volqueta doble troque de alta capacidad para transporte de material de cantera, escombro y llenos en grandes volúmenes.",
    specs: [
      { label: "Capacidad de carga", value: "14 m³" },
      { label: "Peso bruto vehicular", value: "30.000 kg" },
      { label: "Motor", value: "400 HP" },
      { label: "Configuración de ejes", value: "3 ejes (doble troque)" },
      { label: "Año", value: "2018" },
    ],
  },
  {
    code: "VQ-02",
    name: "Volqueta International 4300",
    type: "Volqueta sencilla",
    status: "MAINTENANCE",
    location: "Taller Rionegro",
    client: "Sin asignar",
    hours: "142.900 km",
    since: "desde 18 jul",
    updated: "Hoy 08:10 · operario W. Ospina",
    photo: MACHINE_PHOTO,
    suggestedRate: 85_000,
    publicDescription:
      "Volqueta sencilla ágil para obra urbana y transporte de material en vías de acceso restringido.",
    specs: [
      { label: "Capacidad de carga", value: "7 m³" },
      { label: "Peso bruto vehicular", value: "15.000 kg" },
      { label: "Motor", value: "230 HP" },
      { label: "Configuración de ejes", value: "2 ejes (sencilla)" },
      { label: "Año", value: "2016" },
    ],
  },
  {
    code: "RD-01",
    name: "Rodillo BOMAG BW 213",
    type: "Rodillo compactador",
    status: "AVAILABLE",
    location: "Patio de máquinas Rionegro",
    client: "Sin asignar",
    hours: "6.230 h",
    since: "desde 11 jul",
    updated: "Hoy 07:00 · operario S. Ríos",
    photo: MACHINE_PHOTO,
    suggestedRate: 150_000,
    publicDescription:
      "Rodillo compactador liso para bases, sub-bases y capas asfálticas — control de vibración de alta precisión.",
    specs: [
      { label: "Peso operativo", value: "12.700 kg" },
      { label: "Ancho de rodillo", value: "2,13 m" },
      { label: "Frecuencia de vibración", value: "30 Hz" },
      { label: "Potencia", value: "100 kW (134 HP)" },
      { label: "Año", value: "2021" },
    ],
  },
  {
    code: "MN-01",
    name: "Motoniveladora CAT 120K",
    type: "Motoniveladora",
    status: "WORKING",
    location: "Vía municipal K3+100",
    client: "Municipio de Rionegro",
    hours: "11.050 h",
    since: "desde 14 jul",
    updated: "Hoy 06:15 · operario C. Vélez",
    photo: MACHINE_PHOTO,
    suggestedRate: 150_000,
    publicDescription:
      "Motoniveladora de precisión para conformación y nivelación de vías, terraplenes y placas de urbanización.",
    specs: [
      { label: "Potencia", value: "125 kW (168 HP)" },
      { label: "Peso operativo", value: "14.700 kg" },
      { label: "Ancho de la cuchilla", value: "3,7 m" },
      { label: "Año", value: "2019" },
    ],
  },
  {
    code: "CG-01",
    name: "Cargador CAT 950M",
    type: "Cargador de ruedas",
    status: "AVAILABLE",
    location: "Patio de máquinas Rionegro",
    client: "Sin asignar",
    hours: "8.760 h",
    since: "desde 6 jul",
    updated: "Ayer 16:40 · operario J. Muñoz",
    photo: MACHINE_PHOTO,
    suggestedRate: 110_000,
    publicDescription:
      "Cargador de ruedas para descapote, cargue de material y patio — ciclos rápidos y gran capacidad de cucharón.",
    specs: [
      { label: "Potencia", value: "179 kW (240 HP)" },
      { label: "Peso operativo", value: "18.500 kg" },
      { label: "Capacidad de cucharón", value: "2,7 m³" },
      { label: "Año", value: "2020" },
    ],
  },
  {
    code: "EX-02",
    name: "Excavadora CAT 313",
    type: "Excavadora de orugas",
    status: "MAINTENANCE",
    location: "Taller Rionegro",
    client: "Sin asignar",
    hours: "18.230 h",
    since: "desde 22 jul",
    updated: "Hoy 09:05 · operario A. Ceballos",
    photo: MACHINE_PHOTO,
    suggestedRate: 100_000,
    publicDescription:
      "Excavadora compacta de orugas, ágil en espacios reducidos — zanjeo, redes y obra urbana.",
    specs: [
      { label: "Potencia", value: "68 kW (91 HP)" },
      { label: "Peso operativo", value: "13.700 kg" },
      { label: "Capacidad de cucharón", value: "0,52 m³" },
      { label: "Alcance máx. de excavación", value: "7,7 m" },
      { label: "Año", value: "2017" },
    ],
  },
];

/** Mantenimientos en curso — vinculados 1:1 con el Expense REPARACION que generó su costo. */
export const maintenanceRecords: MaintenanceRecord[] = [
  {
    id: "MNT-0001",
    machineCode: "VQ-02",
    reason: "Reparación sistema de frenos",
    startDate: "18 jul",
    estimatedDays: 8,
    cost: 3_100_000,
    hasInvoice: true,
    status: "EN_CURSO",
    expenseId: "GAS-0428",
  },
  {
    id: "MNT-0002",
    machineCode: "EX-02",
    reason: "Cambio de bomba hidráulica · mantenimiento preventivo 18.000 h",
    startDate: "22 jul",
    estimatedDays: 5,
    cost: 4_200_000,
    hasInvoice: true,
    status: "EN_CURSO",
    expenseId: "GAS-0432",
  },
];

/** Historial de simulaciones ya hechas en el cotizador. */
export const quotes: Quote[] = [
  {
    id: "COT-0001",
    machineCode: "EX-01",
    clientName: "Constructora Andina S.A.S.",
    hours: 120,
    ratePerHour: 120_000,
    total: 14_400_000,
    date: "15 jul",
  },
];
