import type { Client, Expense, Invoice, Machine, PayrollEntry } from "./types";

export const clients: Client[] = [
  {
    id: "andina",
    name: "Constructora Andina S.A.S.",
    contact: "Carlos Restrepo",
    phone: "314 552 8890",
    services: 7,
  },
  {
    id: "rionegro",
    name: "Municipio de Rionegro",
    contact: "Marcela Duque",
    phone: "301 447 2210",
    services: 4,
  },
  {
    id: "ceja",
    name: "Urbanizadora La Ceja",
    contact: "Fernando Gómez",
    phone: "310 890 4471",
    services: 5,
  },
  {
    id: "vialpisos",
    name: "Vialpisos Ltda.",
    contact: "Diana Correa",
    phone: "300 118 5523",
    services: 3,
  },
  {
    id: "guarne",
    name: "Inversiones Guarné",
    contact: "Julián Zapata",
    phone: "312 664 9081",
    services: 2,
  },
];

export const invoices: Invoice[] = [
  {
    id: "FAC-0182",
    clientId: "andina",
    concept: "Alquiler excavadora EX-01 · 240 h · Vía Rionegro–La Ceja",
    amount: 28_400_000,
    status: "PENDING",
    date: "12 jul 2026",
    due: "Vencida 12 días",
    overdue: true,
    photo: true,
  },
  {
    id: "FAC-0189",
    clientId: "rionegro",
    concept: "Nivelación de vía · motoniveladora MN-01 · 96 h",
    amount: 14_680_000,
    status: "PENDING",
    date: "18 jul 2026",
    due: "Vence 28 jul",
    overdue: false,
    photo: false,
  },
  {
    id: "FAC-0191",
    clientId: "ceja",
    concept: "Transporte de material · volqueta VQ-02 · 38 viajes",
    amount: 11_000_000,
    status: "PENDING",
    date: "20 jul 2026",
    due: "Vence 30 jul",
    overdue: false,
    photo: false,
  },
  {
    id: "FAC-0176",
    clientId: "vialpisos",
    concept: "Compactación con rodillo RD-01 · 60 h",
    amount: 9_200_000,
    status: "PAID",
    date: "8 jul 2026",
    due: "Pagada 15 jul",
    overdue: false,
    photo: true,
  },
  {
    id: "FAC-0170",
    clientId: "andina",
    concept: "Alquiler retroexcavadora RX-01 · 180 h",
    amount: 21_500_000,
    status: "PAID",
    date: "3 jul 2026",
    due: "Pagada 10 jul",
    overdue: false,
    photo: true,
  },
  {
    id: "FAC-0164",
    clientId: "guarne",
    concept: "Cargador CG-01 · descapote 500 m³",
    amount: 7_620_000,
    status: "PAID",
    date: "1 jul 2026",
    due: "Pagada 6 jul",
    overdue: false,
    photo: true,
  },
];

export const payroll: PayrollEntry[] = [
  { name: "Jhon Muñoz", role: "Operario excavadora EX-01", amount: 2_600_000, paid: true },
  { name: "Andrés Ceballos", role: "Operario retroexcavadora RX-01", amount: 2_450_000, paid: true },
  { name: "Wilmer Ospina", role: "Operario volqueta VQ-02", amount: 1_980_000, paid: true },
  { name: "Sebastián Ríos", role: "Operario rodillo RD-01", amount: 1_850_000, paid: false },
  { name: "Camilo Vélez", role: "Operario motoniveladora MN-01", amount: 2_120_000, paid: true },
];

export const expenses: Expense[] = [
  {
    id: "GAS-0431",
    cat: "SUELDO",
    desc: "Nómina de operarios · 2da quincena",
    amount: 11_000_000,
    date: "25 jul",
    machine: "—",
    photo: false,
  },
  {
    id: "GAS-0430",
    cat: "GASOLINA",
    desc: "Combustible flota · surtido semanal",
    amount: 4_600_000,
    date: "22 jul",
    machine: "EX-01",
    photo: true,
  },
  {
    id: "GAS-0429",
    cat: "REPUESTO",
    desc: "Cambio de filtros hidráulicos",
    amount: 2_450_000,
    date: "20 jul",
    machine: "EX-01",
    photo: true,
  },
  {
    id: "GAS-0428",
    cat: "REPARACION",
    desc: "Reparación sistema de frenos",
    amount: 3_100_000,
    date: "18 jul",
    machine: "VQ-02",
    photo: true,
  },
  {
    id: "GAS-0427",
    cat: "PUNTO",
    desc: "Papelería y viáticos de gerencia",
    amount: 620_000,
    date: "16 jul",
    machine: "—",
    photo: false,
  },
  {
    id: "GAS-0426",
    cat: "GASOLINA",
    desc: "Combustible motoniveladora",
    amount: 1_980_000,
    date: "14 jul",
    machine: "MN-01",
    photo: true,
  },
  {
    id: "GAS-0425",
    cat: "REPUESTO",
    desc: "Llantas rodillo RD-01",
    amount: 3_800_000,
    date: "11 jul",
    machine: "RD-01",
    photo: false,
  },
  {
    id: "GAS-0424",
    cat: "SUELDO",
    desc: "Nómina de operarios · 1ra quincena",
    amount: 11_000_000,
    date: "10 jul",
    machine: "—",
    photo: false,
  },
  {
    id: "GAS-0423",
    cat: "PUNTO",
    desc: "Alimentación cuadrilla obra Rionegro",
    amount: 480_000,
    date: "6 jul",
    machine: "—",
    photo: false,
  },
];

/**
 * Fotos de referencia por tipo de máquina — placeholders reales tomados de
 * Wikimedia Commons (dominio público / licencia libre) mientras la empresa
 * sube fotos propias de cada activo desde la hoja del semáforo.
 */
const STOCK_PHOTO = {
  excavadora: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Excavator_0025.jpg",
  retroexcavadora:
    "https://upload.wikimedia.org/wikipedia/commons/f/f5/JCB_3CX_backhoe_loader.JPG",
  volqueta: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Caterpillar_dump_truck.jpg",
  rodillo: "https://upload.wikimedia.org/wikipedia/commons/7/77/A_Road_roller.JPG",
  motoniveladora:
    "https://upload.wikimedia.org/wikipedia/commons/d/d4/Caterpillar_12G_grader_MD3.jpg",
  cargador:
    "https://upload.wikimedia.org/wikipedia/commons/1/18/Caterpillar_950k_Wheel_Loader.jpg",
} as const;

export const machines: Machine[] = [
  {
    code: "EX-01",
    name: "Excavadora CAT 320D",
    type: "Excavadora de orugas",
    status: "WORKING",
    location: "Vía Rionegro–La Ceja · K12+400",
    client: "Constructora Andina S.A.S.",
    hours: "14.820 h",
    since: "desde 12 mar",
    updated: "Hoy 06:40 · operario J. Muñoz",
    photo: STOCK_PHOTO.excavadora,
  },
  {
    code: "RX-01",
    name: "Retroexcavadora CASE 580",
    type: "Retroexcavadora",
    status: "WORKING",
    location: "Urbanización La Ceja · Etapa 2",
    client: "Urbanizadora La Ceja",
    hours: "9.410 h",
    since: "desde 3 jul",
    updated: "Ayer 17:20 · operario A. Ceballos",
    photo: STOCK_PHOTO.retroexcavadora,
  },
  {
    code: "VQ-01",
    name: "Volqueta Kenworth 750",
    type: "Volqueta doble troque",
    status: "WORKING",
    location: "Cantera El Peñol",
    client: "Vialpisos Ltda.",
    hours: "186.400 km",
    since: "desde 20 jul",
    updated: "Hoy 05:55 · operario W. Ospina",
    photo: STOCK_PHOTO.volqueta,
  },
  {
    code: "VQ-02",
    name: "Volqueta International 4300",
    type: "Volqueta sencilla",
    status: "MAINTENANCE",
    location: "Taller Rionegro",
    client: "Sin asignar",
    hours: "142.900 km",
    since: "desde 18 jul",
    updated: "Hoy 08:10 · operario W. Ospina",
    photo: STOCK_PHOTO.volqueta,
  },
  {
    code: "RD-01",
    name: "Rodillo BOMAG BW 213",
    type: "Rodillo compactador",
    status: "AVAILABLE",
    location: "Patio de máquinas Rionegro",
    client: "Sin asignar",
    hours: "6.230 h",
    since: "desde 11 jul",
    updated: "Hoy 07:00 · operario S. Ríos",
    photo: STOCK_PHOTO.rodillo,
  },
  {
    code: "MN-01",
    name: "Motoniveladora CAT 120K",
    type: "Motoniveladora",
    status: "WORKING",
    location: "Vía municipal K3+100",
    client: "Municipio de Rionegro",
    hours: "11.050 h",
    since: "desde 14 jul",
    updated: "Hoy 06:15 · operario C. Vélez",
    photo: STOCK_PHOTO.motoniveladora,
  },
  {
    code: "CG-01",
    name: "Cargador CAT 950M",
    type: "Cargador de ruedas",
    status: "AVAILABLE",
    location: "Patio de máquinas Rionegro",
    client: "Sin asignar",
    hours: "8.760 h",
    since: "desde 6 jul",
    updated: "Ayer 16:40 · operario J. Muñoz",
    photo: STOCK_PHOTO.cargador,
  },
  {
    code: "EX-02",
    name: "Excavadora CAT 313",
    type: "Excavadora de orugas",
    status: "MAINTENANCE",
    location: "Taller Rionegro",
    client: "Sin asignar",
    hours: "18.230 h",
    since: "desde 22 jul",
    updated: "Hoy 09:05 · operario A. Ceballos",
    photo: STOCK_PHOTO.excavadora,
  },
];
